# These are used by GitHub to render the "Sponsor" button on the repo.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Dmitrze]
custom: ['https://dmitrymelnik.ai']

# Future: open-collective, ko-fi, etc.
# open_collective:
# tidelift: "cargo/repo-trust"
