# These are used by GitHub to render the "Sponsor" button on the repo.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Dmitrze]

# Future: open-collective, ko-fi, etc.
# open_collective:
# tidelift: "cargo/repo-trust"
# custom: ["https://..."]
